version: "3.4"

# This compose override file should be used like so:
# docker-compose -f docker-compose.yml -f docker-compose.local.yml
#
# It adds build sections and overrides the image params for each service allowing the
# Baserow individual service images to be built and tested locally.
services:

  backend:
    image: baserow_backend:latest
    build:
      dockerfile: ./backend/Dockerfile
      context: .

  celery:
    image: baserow_backend:latest
    environment:
      EMAIL_SMTP: 'yes'
      EMAIL_SMTP_HOST: 'mailhog'
      EMAIL_SMTP_PORT: '1025'
    build:
      dockerfile: ./backend/Dockerfile
      context: .

  celery-export-worker:
    image: baserow_backend:latest
    build:
      dockerfile: ./backend/Dockerfile
      context: .

  celery-beat-worker:
    image: baserow_backend:latest
    build:
      dockerfile: ./backend/Dockerfile
      context: .

  web-frontend:
    image: baserow_web-frontend:latest
    build:
      dockerfile: ./web-frontend/Dockerfile
      context: .

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "8025:8025" # web ui
    networks:
      local:

  # When switching between dev and local the media files in the media volume will be
  # owned by different users. Ensure that we chown them to the user appropriate for the
  # environment here.
  media-volume-fixer:
    image: bash:4.4
    command: chown 9999:9999 -R /baserow/media
    volumes:
      - media:/baserow/media
    networks:
      local:
